### ISSUE TITLE
Button to use Air Horn

### ISSUE THREAD

**Issue by DaneTank** [real-coco-labs/pz-airhorn#1]
Implement an event that activates Air horn when a button is pressed.
The button can be "Mouse1" because it works like a gun.

**Comment by matshou** [comment]
I am not sure if `Events.OnKeyPressed` fires on mouse buttons. 
Regardless, we should have an alternative keyboard button as well and it should be defined somewhere where it's easy for users to configure (perhaps a separate file clearly indicated to containing only hotkey definitions).
